apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: product-default
spec:
  destination:
    name: productpage 
  route:
  - labels:
      version: dev
    weight: 90
  - labels:
      version: prod
    weight: 10
